import { useEffect, useMemo, useState } from 'react';
const API_BASE = `${import.meta.env.VITE_API_URL || ''}/api`;
type Setor = '' | 'RESULTADO_PRODUTOS' | 'OUTRAS_RECEITAS' | 'DESPESAS';
type Tipo = { id:number; codigo:string; nome:string; setor_relatorio_periodo?:string|null };
const setores:Array<{id:Exclude<Setor,''>;titulo:string;ajuda:string}> = [
  {id:'RESULTADO_PRODUTOS',titulo:'Receitas / Resultado Líquido dos Produtos',ajuda:'Tipos usados para compor o resultado líquido dos produtos.'},
  {id:'OUTRAS_RECEITAS',titulo:'Outras Receitas',ajuda:'Tipos listados e somados como outras receitas do período.'},
  {id:'DESPESAS',titulo:'Despesas pagas no período',ajuda:'Tipos listados e somados como despesas do período.'},
];
export default function RelatorioPeriodoTiposAdminPage(){
  const [tipos,setTipos]=useState<Tipo[]>([]); const [alocacao,setAlocacao]=useState<Record<number,Setor>>({}); const [mensagem,setMensagem]=useState(''); const [salvando,setSalvando]=useState(false);
  async function carregar(){setMensagem('');try{const r=await fetch(`${API_BASE}/relatorio-periodo/tipos`);const j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw new Error(j.erro||'Erro ao carregar os tipos.');const lista:Tipo[]=Array.isArray(j.tipos)?j.tipos:[];setTipos(lista);setAlocacao(Object.fromEntries(lista.map((t)=>[Number(t.id),String(t.setor_relatorio_periodo||'').toUpperCase() as Setor])))}catch(e:any){setMensagem(e.message||'Erro ao carregar os tipos.')}}
  useEffect(()=>{carregar()},[]); const semSetor=useMemo(()=>tipos.filter((t)=>!alocacao[t.id]),[tipos,alocacao]);
  const escolher=(id:number,setor:Setor)=>setAlocacao((a)=>({...a,[id]:a[id]===setor?'':setor}));
  async function salvar(){setSalvando(true);setMensagem('');try{const r=await fetch(`${API_BASE}/relatorio-periodo/tipos`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({tipos:tipos.map((t)=>({id:t.id,setor:alocacao[t.id]||''}))})});const j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw new Error(j.erro||'Erro ao salvar.');setMensagem(j.mensagem||'Configuração salva.')}catch(e:any){setMensagem(e.message||'Erro ao salvar.')}finally{setSalvando(false)}}
  return <div className="admin-tool-page"><section className="admin-tool-hero"><h1>Configuração do Relatório do Período</h1><p>Defina em qual setor cada Tipo de Lançamento (T) será computado. Tipos sem setor não serão listados nem somados.</p></section>{mensagem&&<div className="admin-tool-message">{mensagem}</div>}<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:12}}>{setores.map((setor)=><section className="admin-tool-card" key={setor.id}><h2 style={{marginTop:0}}>{setor.titulo}</h2><p style={{color:'#64748B'}}>{setor.ajuda}</p><div style={{display:'grid',gap:6}}>{tipos.map((t)=><label key={`${setor.id}-${t.id}`} style={{display:'flex',gap:8,alignItems:'center',padding:'7px 8px',border:'1px solid #E2E8F0',borderRadius:7,cursor:'pointer'}}><input type="checkbox" checked={alocacao[t.id]===setor.id} onChange={()=>escolher(t.id,setor.id)}/><span><strong>T{t.id}</strong> — {t.nome} <small style={{color:'#64748B'}}>({t.codigo})</small></span></label>)}</div></section>)}</div><section className="admin-tool-card" style={{marginTop:12}}><h2 style={{marginTop:0}}>Não computar no Relatório do Período</h2><p>Estes tipos ficam fora das listas e de todas as somas:</p><div>{semSetor.length?semSetor.map((t)=><span key={t.id} style={{display:'inline-block',margin:'3px 6px 3px 0',padding:'5px 8px',background:'#F1F5F9',borderRadius:6}}>T{t.id} — {t.nome}</span>):'Nenhum tipo.'}</div></section><div style={{display:'flex',justifyContent:'flex-end',marginTop:12}}><button className="admin-primary-button" type="button" onClick={salvar} disabled={salvando}>{salvando?'Salvando...':'Salvar configuração'}</button></div></div>;
}
